# Changes to anything in the _map subfolder
Map Modification:
- changed-files:
  - any-glob-to-any-file: '_maps/**'

# Changes to a .dmi
Sprites:
<<<<<<< HEAD
- '**/*.dmi'

# Chganges to a /config
Config:
- 'config/**'
=======
- changed-files:
  - any-glob-to-any-file: '**/*.dmi'
>>>>>>> 42c733dc2 (Fixes the labeler in accordance to the new action version (#25430))
